mysite/food/urls.py
from django.urls import path
from . import views
app_name = 'food'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:item_id>/',views.detail,name='detail'),
    path('item/',views.item,name='item'),
    path('add',views.create_item,name='create_item'),
    path('update/<int:id>/',views.update_item,name='update_item'),
     path('delete/<int:id>/',views.delete_item,name='delete_item'),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from users import views as user_views
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/',user_views.register,name="register"),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name="login"),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name="logout"),
]

mysite/food/models.py
from django.db import models

class Item(models.Model):
    def __str__(self):
        return self.item_name
    item_name =models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500 ,default = "https://th.bing.com/th/id/OIP.kRfblRpg8bm4PcJqIF6SRgHaFj?rs=1&pid=ImgDetMain")
     

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

mysite/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm


def index(request):
    item_list = Item.objects.all()
    
    context ={
        'item_list' : item_list,

    }

    return render(request,'food/index.html',context)


def item(request):
    return HttpResponse('<h1>This is an item</h1>')


def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item' : item
    }
    return render(request,'food/detail.html',context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
     item = Item.objects.get(id=id)

     if request.method == "POST" :
         item.delete()
         return redirect('food:index')
     
     return render(request,'food/item-delete.html',{'item':item})
     




mysite/users/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, Your account was created successfully')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form':form})

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>
        <div class="d-flex">
            <a class="nav-item nav-link text-light p-2" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item nav-link text-light p-2" href="#">Delete Item</a>
            <a class="nav-item nav-link text-light p-2" href="#">View Item</a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link text-light p-2" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link text-light p-2" href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
       
    </nav> 
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
      {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
    
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="card img-fluid" src="{{ item.item_image }}" alt="{{ item.item_name }}" style="max-height: 300px; width: 100%;">
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>Rs {{ item.item_price }}</h3>
            <a href="{% url 'food:delete_item' item.id  %}">Delete</a>
        </div>
    </div>
</div>





{% endblock %}


mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
</head>
<body>

{% block body %}


{% for item in item_list %}
    
<div class="row">
    <div class="col-md-3 offset-md-2">
        <img class="card img-fluid" height="150px" src="{{ item.item_image }}" alt="{{ item.item_name }}">
    </div>
    <div class="col-md-4">
        <h3>{{ item.item_name }}</h3>
        <h5>{{ item.item_desc }}</h5>
        <h6>Rs {{ item.item_price }}</h6>
    </div>
    <div class="col-md-2">
        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
    </div>
</div>




{% endfor %}

{% endblock %}
<ul>
    <li>
        <a href="{% url 'food:detail' item.id %}"> {{ item.id }} -- {{ item.item_name }} </a>
    </li>
</ul>


    
</body>
</html>

mysite/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

mysite/users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

mysite/users/templates/users/logout.html
<h1>You have been logged out</h1>

mysite/users/templates/users/register.html
<form method="POST">
     {% csrf_token %}
     {{ form }}
     <button type="submit">Signup</button>
</form>